version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install cfn-lint
      - pip install taskcat

  pre_build:
    commands:
      - echo "Running cfn-lint to validate CloudFormation templates..."
      - cfn-lint ./main.yaml

  build:
    commands:
      - echo "Running Taskcat to test CloudFormation templates..."
      - taskcat test run
